version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12 
    steps:
      - checkout
      - run: npm install
   
      - run:
          name: Publish to NPM
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then 
              npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
              npm publish ~/project 
            else
              echo "Nothing to publish!" 
            fi

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          type: approval
