version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12 
    steps:
      - checkout
      - run: npm install
   
      - run:
          name: Publish to NPM
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then 
              echo "Publish artifact"
            else
              echo "Nothing to publish!" 
            fi

#adding approval
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - request-testing:
          type: approval
          requires:
            - build
